### ISSUE TITLE
In the compressed files with the patches there is a directory __MACOSX

### ISSUE THREAD

**Issue by joaquin-becerra** [AdobeDocs/commerce-knowledge-base.en#56]
In the compressed files with the patches there is a directory __MACOSX.

![imagen](https://github.com/user-attachments/assets/31401f59-d90c-41f2-a576-a3ca90d94628)

I guess they shouldn't be there

**Comment by barnato-v** [comment]
Hi @joaquin-becerra 

Thank you so much for letting us know. I will find a subject matter expert to investigate. Jira here https://jira.corp.adobe.com/browse/MSKB-2683

**Comment by barnato-v** [comment]
Hi @joaquin-becerra 

I was a bit puzzled when I started looking into this because I couldn’t see the directory on my Mac after downloading the patch. It seems like your UI is based on Linux, which sometimes displays files differently than Mac or Windows.

After chatting with a subject matter expert, I found out that you can just ignore the directory. It’s pretty common when creating zip files. Thanks for pointing this out! I’ll go ahead and close the issue and the Jira ticket I created.
